---
  .travis.yml:
    hc_secure: "QhOLO+ewAaQSy4fwh2e/7DcAfmWDdAaIc/UJ1oP0alhyReFgMaVirYjyPc4G2ilhzqv8XoIF66bdbpehtiFFrHSvGjH3Lhj8650Fsq+8pGNkS02csbMyysSIsCcDgAwxsh4KT1eLxjoR1c+VN4FlK92g+4ZTIbuk59Y90L8vfAo="

