---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: QhOLO+ewAaQSy4fwh2e/7DcAfmWDdAaIc/UJ1oP0alhyReFgMaVirYjyPc4G2ilhzqv8XoIF66bdbpehtiFFrHSvGjH3Lhj8650Fsq+8pGNkS02csbMyysSIsCcDgAwxsh4KT1eLxjoR1c+VN4FlK92g+4ZTIbuk59Y90L8vfAo=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: always
  on_failure: always
